# **Clase MinTic ejercicios practicos**
Johan Sebastian Castillo Camargo

# Introdución
En este se usara esta notebook para proporcionar una introducción a SQL, lenguaje imprescindible para todo analista de datos mediante la herramienta colab, este ejercicio se encuentra en el repositorio de kaggle por Gustavo Jaramillo, el ejercicio a trabajar corresponde a una base de datos de fútbol definitiva para análisis de datos y aprendizaje automático.

*   https://www.kaggle.com/code/gustavojaramillo/data-analysis-using-sql-espa-ol
*   https://www.youtube.com/watch?v=9D03JN-EeU0

In [ ]:
#Importación de librerías
import pandas as pd
import sqlite3 ###as SQLite

In [ ]:
# Los datos de entrada están disponibles en el directorio "../input/".
path = "../input/"
database = path + 'database.sqlite'

In [ ]:
## Se incluye el dataframe de la carpeta drive a colab.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Los datos de entrada están disponibles en el drive creamos la conexión .
path ="/content/drive/MyDrive/"

database = path + 'database.sqlite'

## Creamos la conexión con la BD y listaremos las tablas con las que contamos

conn = sqlite3.connect(database)
print ("Conexión exitosa")

print(database)

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""",conn)


tables

Conexión exitosa
/content/drive/MyDrive/database.sqlite

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

# 2. Sentencia SELECT
Esta es la consulta más básica y su estructura es muy simple:

Se define lo que se quiere ver después del SELECT
Se eligen las tablas a consultar después del FROM
Las únicas partes imprescindibles de una consulta son el SELECT y el FROM.

La sintaxis de esta consulta es así:

SELECT column1, column2, ...

FROM table_name;

Para consultar por todos los campos en una tabla sin tener que escribir uno por uno el nombre de cada campo, se utiliza SELECT *

SELECT * significa que quieres obtener todas las columnas posibles de la tabla consultada. Los datos devueltos se almacenan en una tabla de resultados, denominada conjunto de resultados.

La sintaxis de esta consulta es así:

SELECT *

FROM table_name;

Es una buena práctica terminar la consulta con un punto y coma para indicar que la consulta está completa. Las palabras clave se escriben en mayúsculas y los nombres de tablas y campos se escriben en minúsculas.

## 2.1.1 Ejemplo: Listar los países

Queremos consultar qué países se encuentran en la tabla Country de la base de datos del fútbol europeo.

Importante: La estructura y el orden de las secciones son importantes, mientras que los espacios, las nuevas líneas, las mayúsculas y las sangrías están ahí para facilitar la lectura del código.

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
query = """SELECT *
           FROM Country; """

countries = pd.read_sql(query, conn)
countries

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

# 2.1.2 Práctica: Listar las ligas del fútbol europeo
Deben listar todas las ligas que estén en la tabla League de la base de datos de fútbol europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" justo después de la palabra query =

Una vez que estén lo tengan listo, ejecuten haciendo clic en ejecutar (o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" justo después de la palabra query =

query = """SELECT *
           FROM League; """

# Filtramos la liga francesa la base de datos.
### query = """SELECT * FROM League WHERE name like '%france%'; """

#No modificar lo siguiente:
leagues = pd.read_sql(query, conn)
leagues

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

# 2.1.3 Práctica: Listar los jugadores del fútbol europeo
Deben listar los campos id,player_name, birthday, height y weight que estan en la tabla Player de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """Select *
           FROM Player;"""

#No modificar lo siguiente:
players = pd.read_sql(query, conn)
players

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
...,...,...,...,...,...,...,...
11055,11071,26357,Zoumana Camara,2488,1979-04-03 00:00:00,182.88,168
11056,11072,111182,Zsolt Laczko,164680,1986-12-18 00:00:00,182.88,176
11057,11073,36491,Zsolt Low,111191,1979-04-29 00:00:00,180.34,154
11058,11074,35506,Zurab Khizanishvili,47058,1981-10-06 00:00:00,185.42,172
11059,11075,39902,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176

# 2.2 Sentencia SELECT DISTINCT
La sentencia SELECT DISTINCT se utiliza para devolver sólo valores distintos (diferentes).

Dentro de una tabla, una columna a menudo contiene muchos valores duplicados y a veces sólo se desea listar los diferentes valores (distintos).

La sintaxis de SELECT DISTINCT es así:

SELECT DISTINCT column1

FROM table_name;

2.2.1 Ejemplo: Listar las temporadas jugadas de esta Base de Datos
Si consultamos por todas las temporadas que se almacenaron en la tabla Matchde la base de datos de Fútbol Europeo, vamos a tener el siguiente resultado.

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
# Registran 25979 resultados.

query = """
SELECT season
FROM Match;
"""
seasons = pd.read_sql(query, conn)
seasons

          season
0      2008/2009
1      2008/2009
2      2008/2009
3      2008/2009
4      2008/2009
...          ...
25974  2015/2016
25975  2015/2016
25976  2015/2016
25977  2015/2016
25978  2015/2016

[25979 rows x 1 columns]

Con el resultado anterior, es muy difícil responder a la pregunta ¿Cuáles son las temporadas almacenadas en esta base de datos? Para responderla sin mucho esfuerzo, usamos SELECT DISTINCT para consultar la tabla Match de la base de datos.

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
# Solo se registran 8 tempoadas del analisis comprendidas del 2008 al 2016

query = """
SELECT DISTINCT season
FROM Match;
"""
seasons = pd.read_sql(query, conn)
seasons

      season
0  2008/2009
1  2009/2010
2  2010/2011
3  2011/2012
4  2012/2013
5  2013/2014
6  2014/2015
7  2015/2016

# 2.2.2 Práctica: Listar sólo tasas diferentes de valoración general de los jugadores.
En la tabla Player_Attributes de la base de datos de Fútbol Europeo hay el campo overall_rating que parece contener la valoración de los jugadores. El objetivo es ver sólo tasas diferentes de valoración general de los jugadores.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

# Se evidencia toda la informacion de nuestra tabla Player_Attributes
query = """ SELECT DISTINCT overall_rating
            FROM Player_Attributes """

# Sacamos el promedio
#query = """ SELECT AVG(overall_rating) as Promedio
#           FROM Player_Attributes """

#No modificar lo siguiente:
overall_rating = pd.read_sql(query, conn)
overall_rating

    overall_rating
0             67.0
1             62.0
2             61.0
3             74.0
4             73.0
..             ...
57            33.0
58            36.0
59            37.0
60            35.0
61            94.0

[62 rows x 1 columns]

# 3. Sentencia LIMIT
Cuando deseamos poner un límite al resultado o no nos interesa conocer la totalidad de los resultados, podemos limitar la cantidad de registros resultantes mediante la sentencia LIMIT

La sintaxis de LIMIT es así:

SELECT column1, column2...

FROM table_name

LIMIT number;

3.1.1 Ejemplo: Listar 15 jugadores de la base de datos del fútbol europeo
Queremos listar 15 jugadores de la tabla Player de la base de datos de Fútbol Europeo. En la tabla de resultados quiero ver los campos ìd,player_name, birthday, height y weight. Todos se encuentran en la tabla Player

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
# De nuestra tabla Player se muestran los 15 primeros jugadores de la lista.
query = """ SELECT id, player_name, birthday, height, weight
            FROM Player
            LIMIT 15; """


players = pd.read_sql(query, conn)
players

    id         player_name             birthday  height  weight
0    1  Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
1    2     Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2    3         Aaron Doran  1991-05-13 00:00:00  170.18     163
3    4       Aaron Galindo  1982-05-08 00:00:00  182.88     198
4    5        Aaron Hughes  1979-11-08 00:00:00  182.88     154
5    6          Aaron Hunt  1986-09-04 00:00:00  182.88     161
6    7          Aaron Kuhl  1996-01-30 00:00:00  172.72     146
7    8        Aaron Lennon  1987-04-16 00:00:00  165.10     139
8    9        Aaron Lennox  1993-02-19 00:00:00  190.50     181
9   10       Aaron Meijers  1987-10-28 00:00:00  175.26     170
10  11       Aaron Mokoena  1980-11-25 00:00:00  182.88     181
11  12          Aaron Mooy  1990-09-15 00:00:00  175.26     150
12  13      Aaron Muirhead  1990-08-30 00:00:00  187.96     168
13  14        Aaron Niguez  1989-04-26 00:00:00  170.18     143
14  15        Aaron Ramsey  1990-12-26 00:00:00  177.80     154

# 3.1.2 Práctica: Listar 25 equipos del fútbol europeo
Deben listar 25 equipos del fútbol europeo. La tabla de resultados deberá contener los campos id y team_long_name de la tabla Team de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
# De nuestra tabla Teams se muestran los 25 equipos del futbol Europeo.
query = """ SELECT id,  team_long_name
            FROM Team
            LIMIT 25; """


teams = pd.read_sql(query, conn)
teams

      id        team_long_name
0      1              KRC Genk
1      2          Beerschot AC
2      3      SV Zulte-Waregem
3      4      Sporting Lokeren
4      5     KSV Cercle Brugge
5      6        RSC Anderlecht
6      7              KAA Gent
7      8             RAEC Mons
8      9         FCV Dender EH
9     10     Standard de Liège
10    11           KV Mechelen
11    12        Club Brugge KV
12    13         KSV Roeselare
13    14           KV Kortrijk
14    15                Tubize
15    16  Royal Excel Mouscron
16    17          KVC Westerlo
17    18    Sporting Charleroi
18   614     Sint-Truidense VV
19  1034             Lierse SK
20  1042             KAS Eupen
21  1513   Oud-Heverlee Leuven
22  2004      Waasland-Beveren
23  2476           KV Oostende
24  2510  Royal Excel Mouscron

# 4. Funciones agregativas/ Métricas
Todas las métricas tienen que ser agregadas usando funciones. Las funciones agregativas más comunes son:

SUM() | Sumatoria total de una columna tipo numérica.
COUNT() | Devuelve la cantidad de filas.
COUNT(DISTINCT) | Devuelve la cantidad de filas distintas o diferentes.
AVG() | Promedia los valores de una columna tipo numérica.
MIN() | Menor valor dentro de la columna especificada.
MAX() | Mayor valor dentro de la columna especificada.
La sintaxis de las métricas en la sentencia SELECT es así:

SUM()
SELECT SUM(column1), column2...

FROM table_name

COUNT()
SELECT COUNT(column1), column2...

FROM table_name

COUNT(DISTINCT)
SELECT COUNT(DISTINCT column1), column2...

FROM table_name

AVG()
SELECT AVG(column1), column2...

FROM table_name

MIN()
SELECT MIN(column1), column2...

FROM table_name

MAX()
SELECT MAX(column1), column2...

FROM table_name

4.1.1 Ejemplo: ¿Cuántos países diferentes están almacenados en la tabla Country?
Para consultar por el número de países diferentes almacenados en la tabla Country y que la tabla de resultados nos muestre únicamente el número con la cantidad de países, necesitamos usar una función agregativa que cuente el número de registros pero además, que cuente sólo los registros distintos. Esa función es COUNT(DISTINCT )

Ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
# De nuestra tabla Teams se muestran los 25 equipos del futbol Europeo.
query = """ SELECT COUNT(DISTINCT(name)) AS NumeroPaises
            FROM Country; """


country = pd.read_sql(query, conn)
country

   NumeroPaises
0            11

# Ejercicio Clase # 1



*   Realizar 5 preguntas con su respectiva respuesta de la tabla Player.

In [ ]:
# Total de Jugadores que participaron.
query = """ SELECT COUNT(DISTINCT(player_name)) AS TotalJugadores
            FROM Player; """


players = pd.read_sql(query, conn)
players

   TotalJugadores
0           10848

In [ ]:
# Promedio de Peso de los Jugadores.
query = """ SELECT AVG(weight) as Peso
            FROM Player; """


players = pd.read_sql(query, conn)
players

         Peso
0  168.380289

In [ ]:
# Jugador con el Peso mas alto.
query = """ SELECT player_name as Jugador, MAX(weight) AS Peso
            FROM Player; """


players = pd.read_sql(query, conn)
players

            Jugador  Peso
0  Kristof van Hout   243

In [ ]:
# Jugador con el Peso mas bajo.
query = """ SELECT player_name as Jugador, MIN(weight) AS Peso
            FROM Player; """


players = pd.read_sql(query, conn)
players

      Jugador  Peso
0  Juan Quero   117

In [ ]:
# Promedio de Altura de los Jugadores.
query = """ SELECT AVG(height) as Altura, AVG(weight) as Peso
            FROM Player; """


players = pd.read_sql(query, conn)
players

       Altura        Peso
0  181.867445  168.380289

In [ ]:
# Identificamos la lista de los Jugamodres mas Jovenes.
query = """ SELECT player_name AS Jugadores, birthday as FechaCumpleaños
            FROM Player
            ORDER BY birthday DESC; """


players = pd.read_sql(query, conn)
players

                  Jugadores      FechaCumpleaños
0             Jonathan Leko  1999-04-24 00:00:00
1      Gianluigi Donnarumma  1999-02-25 00:00:00
2              Alban Lafont  1999-01-23 00:00:00
3      Kylian Mbappe Lottin  1998-12-20 00:00:00
4              Reece Oxford  1998-12-16 00:00:00
...                     ...                  ...
11055          Dean Windass  1969-04-01 00:00:00
11056            Luca Bucci  1969-03-13 00:00:00
11057          Rob van Dijk  1969-01-15 00:00:00
11058         Paolo Maldini  1968-06-26 00:00:00
11059       Alberto Fontana  1967-01-23 00:00:00

[11060 rows x 2 columns]

## 4.1.2 Práctica: Traer el número de etapas jugadas de la tabla Match
Deben traer el número de etapas stage almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con la cantidad de etapas diferentes.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

## 4.1.2 Práctica: Traer el número de etapas jugadas de la tabla Match
query = """ SELECT COUNT(DISTINCT(stage)) AS Cantidad_Etapas FROM Match """

#No modificar lo siguiente:
countdis_stages = pd.read_sql(query, conn)
countdis_stages

   Cantidad_Etapas
0               38

## 4.1.3 Práctica: Traer la suma de goles hechos por los equipos visitantes de la tabla Match.
Deben traer la suma de goles hechos por los equipos visitantes away_team_goal almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con la suma de goles.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """ SELECT SUM(away_team_goal) as TotalGolesVisitantes FROM Match """

#No modificar lo siguiente:
sum_awayteam = pd.read_sql(query, conn)
sum_awayteam

   TotalGolesVisitantes
0                 30160

## 4.1.4 Práctica: Traer el promedio de goles hechos por los equipos locales y el promedio de goles hechos por los visitantes de la tabla Match.
Deben traer el promedio de goles hechos por los equipos locales home_team_goal y el promedio de goles hechos por los equipos visitantes away_team_goal almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con el promedio de goles.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """ SELECT AVG(home_team_goal) as TotalGolesLocales,
                   AVG(away_team_goal) as TotalGolesVisitantes FROM Match """

#No modificar lo siguiente:
avg_teamgoals = pd.read_sql(query, conn)
avg_teamgoals

   TotalGolesLocales  TotalGolesVisitantes
0           1.544594              1.160938

## 4.1.5 Práctica: Traer la máxima cantidad de goles que un equipo visitante anotó en los juegos de la tabla Match
Deben traer la máxima cantidad de goles un equipo visitante away_team_goal almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con cantidad de goles.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """ SELECT MAX(away_team_goal) as MaxGolesVisitantes FROM Match """

#No modificar lo siguiente:
max_teamgoals = pd.read_sql(query, conn)
max_teamgoals

   MaxGolesVisitantes
0                   9

## 5. Operaciones matemáticas
Se pueden realizar operaciones matemáticas como: +, -, *, /, etc. Asimismo, estás operaciones pueden ser usadas en conjunto con las funciones agregativas/ métricas.

La sintaxis en la sentencia SELECT es así:

+
SELECT column1+column2

FROM table_name

La sintaxis combinando con una métrica en la sentencia SELECT es así:

AVG(+)
SELECT AVG(column1+column2)

FROM table_name

## 5.1.1 Práctica: Traer el promedio de goles por partido de la tabla Match
Deben traer el promedio de la suma de goles hechos por los equipos locales home_team_goal y visitantes away_team_goal en todos los juegos almacenados en la tabla Match de la base de datos de Fútbol Europeo. La tabla de resultados deberá mostrar únicamente el número con el promedio de goles por partido.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """ SELECT AVG(home_team_goal)+
                   AVG(away_team_goal) as Promedio_de_la_suma_Visitantes_y_Locales FROM Match """

#No modificar lo siguiente:
avg_teamgoals = pd.read_sql(query, conn)
avg_teamgoals

#No modificar lo siguiente:
avg_sum_goals = pd.read_sql(query, conn)
avg_sum_goals

   Promedio_de_la_suma_Visitantes_y_Locales
0                                  2.705531

## 6. Sentencia WHERE
La sentencia WHERE se utiliza para filtrar registros. Mediante esta sentencia, se extraen sólo aquellos registros que cumplen una condición específica.

La sintaxis de WHERE es así:

SELECT column1, column2...

FROM table_name

WHERE condition;

6.1 Campos de texto (y fecha) vs campos numéricos
SQL requiere comillas simples alrededor de los valores del texto y fecha (la mayoría de los sistemas de bases de datos también permiten comillas dobles). Sin embargo, los campos numéricos no deben incluirse entre comillas.

Ejemplos de sintaxis con campo númerico:

SELECT *

FROM Customers

WHERE CustomerId = 1;

Ejemplos de sintaxis con campo de texto:

SELECT *

FROM Customers

WHERE Country = 'Mexico';

## 6.2.1 Ejemplo: Listar los jugadores que pesan 165 libras.
Queremos listar a los jugadores que cumplan con la condición de pesar 165 libras. En la tabla de resultados quiero ver los campos id,player_name, birthday, height y weight de los que cumplen la condición. Todos se encuentran en la tabla Player

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
query = """SELECT id, player_name, birthday, height, weight
        FROM Player
        WHERE weight = 165
        LIMIT 15;"""

players_weight = pd.read_sql(query, conn)
players_weight

     id          player_name             birthday  height  weight
0    27   Abdelmalek Cherrad  1981-01-14 00:00:00  185.42     165
1    44   Abdoulaye Doucoure  1993-01-01 00:00:00  182.88     165
2    46      Abdoulaye Keita  1994-01-05 00:00:00  175.26     165
3    49  Abdoulwahid Sissoko  1990-03-20 00:00:00  182.88     165
4    58   Abdullah Al Hafith  1992-12-25 00:00:00  187.96     165
5    62           Abel Gomez  1982-02-20 00:00:00  182.88     165
6    67                 Abel  1978-12-22 00:00:00  177.80     165
7    69         Abiola Dauda  1988-02-03 00:00:00  180.34     165
8    78     Abraham Paz Cruz  1979-03-14 00:00:00  177.80     165
9    84          Aco Stojkov  1983-04-29 00:00:00  177.80     165
10  110            Adam King  1995-10-11 00:00:00  180.34     165
11  119       Adam Matuschyk  1989-02-14 00:00:00  180.34     165
12  132            Adam Vass  1988-09-09 00:00:00  180.34     165
13  157        Adnan Januzaj  1995-02-05 00:00:00  182.88     165
14  169   Adrian Klepczynski  1981-04-01 00:00:00  187.96     165

## 6.2.2 Práctica: Listar las temporadas en que un equipo visitante anotó 7 o más goles
Deben listar las temporadas en que algún equipo visitante haya anotado 7 o más goles. La tabla de resultados deberá contener los campos season, home_team_goal, away_team_goal de la tabla Match de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT season, home_team_goal,away_team_goal
        FROM Match
        WHERE away_team_goal > 7"""

#No modificar lo siguiente:
away_team_goals = pd.read_sql(query, conn)
away_team_goals

      season  home_team_goal  away_team_goal
0  2015/2016               0               9
1  2010/2011               1               8
2  2010/2011               0               8
3  2014/2015               0               8
4  2014/2015               2               8
5  2015/2016               0               8

## 6.3 Operadores lógicos en WHERE
La sentencia WHERE puede combinarse con los operadores lógicos: AND, OR y NOT. Los operadores AND y OR se utilizan para filtrar registros basados en más de una condición.

El operador AND muestra un registro si todas las condiciones separadas por AND son VERDADERA(s).
El operador OR muestra un registro si alguna de las condiciones separadas por OR es VERDADERA(s).
El operador NOT muestra un registro si la(s) condición(es) NO es VERDADERA(s).
Sintaxis deAND:
SELECT column1, column2, ...

FROM table_name

WHERE condition1 AND condition2 AND condition3 ...;

Sintaxis de OR
SELECT column1, column2, ...

FROM table_name

WHERE condition1 OR condition2 ...;

Sintaxis de NOT
SELECT column1, column2, ...

FROM table_name

WHERE NOT condition;

## 6.3.1 Práctica: Traer el Id de los equipos que desarrollan un dribbling normal y su velocidad de juego es balanceada
Tomando la tabla Team_Attributes de la base de datos de Fútbol Europeo, deben obtener el id,buildUpPlayDribblingClass y buildUpPlaySpeedClass de los equipos que tengan los siguientes atributos:

buildUpPlayDribblingClass = 'Normal'
buildUpPlaySpeedClass = 'Balanced'
Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT  id, buildUpPlayDribblingClass, buildUpPlaySpeedClass
           FROM Team_Attributes
           WHERE buildUpPlayDribblingClass = 'Normal' AND buildUpPlaySpeedClass = 'Balanced' """

#No modificar lo siguiente:
team_att_and = pd.read_sql(query, conn)
team_att_and

       id buildUpPlayDribblingClass buildUpPlaySpeedClass
0       2                    Normal              Balanced
1       3                    Normal              Balanced
2       8                    Normal              Balanced
3       9                    Normal              Balanced
4      14                    Normal              Balanced
..    ...                       ...                   ...
382  1450                    Normal              Balanced
383  1451                    Normal              Balanced
384  1452                    Normal              Balanced
385  1457                    Normal              Balanced
386  1458                    Normal              Balanced

[387 rows x 3 columns]

## 6.3.2 Práctica: Traer el Id de los equipos que desarrollan un juego de pase largo o su velocidad de juego es rápida.
Tomando la tabla Team_Attributes de la base de datos de Fútbol Europeo, deben obtener el id,buildUpPlayPassingClass y buildUpPlaySpeedClass de los equipos que tengan los siguientes atributos:

buildUpPlayPassingClass = 'Long'
buildUpPlaySpeedClass = 'Fast'
Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query =

#No modificar lo siguiente:
team_att_or = pd.read_sql(query, conn)
team_att_or

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT  id, buildUpPlayPassingClass, buildUpPlaySpeedClass
           FROM Team_Attributes
           WHERE buildUpPlayPassingClass = 'Long' AND buildUpPlaySpeedClass = 'Fast' """


#No modificar lo siguiente:
Match = pd.read_sql(query, conn)
Match

      id buildUpPlayPassingClass buildUpPlaySpeedClass
0      4                    Long                  Fast
1     90                    Long                  Fast
2    167                    Long                  Fast
3    179                    Long                  Fast
4    183                    Long                  Fast
5    225                    Long                  Fast
6    289                    Long                  Fast
7    336                    Long                  Fast
8    359                    Long                  Fast
9    419                    Long                  Fast
10   536                    Long                  Fast
11   555                    Long                  Fast
12   564                    Long                  Fast
13   586                    Long                  Fast
14   611                    Long                  Fast
15   612                    Long                  Fast
16   642                    Long                  Fast
17   713                    Long                  Fast
18   830                    Long                  Fast
19   853                    Long                  Fast
20   899                    Long                  Fast
21   908                    Long                  Fast
22  1002                    Long                  Fast
23  1014                    Long                  Fast
24  1037                    Long                  Fast
25  1216                    Long                  Fast
26  1239                    Long                  Fast
27  1245                    Long                  Fast
28  1246                    Long                  Fast
29  1367                    Long                  Fast
30  1388                    Long                  Fast
31  1389                    Long                  Fast
32  1399                    Long                  Fast
33  1421                    Long                  Fast
34  1423                    Long                  Fast

## 6.3.3 Práctica: Traer la tabla de países sin Bélgica
Deben filtrar la tabla de países y traerla sin Belgium. La tabla de resultados deberá contener los campos id y name de la tabla Country de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT  *
           FROM Country
           WHERE not name  = 'Belgium' """

#No modificar lo siguiente:
countries_not = pd.read_sql(query, conn)
countries_not

      id         name
0   1729      England
1   4769       France
2   7809      Germany
3  10257        Italy
4  13274  Netherlands
5  15722       Poland
6  17642     Portugal
7  19694     Scotland
8  21518        Spain
9  24558  Switzerland

## 6.4 Otros operadores que trabajan con la sentencia WHERE
Los siguientes operadores también pueden ser utilizados en la sentencia WHERE:

| = | Igual

| > | Mayor que

| < | Menor que

| >= | Mayor o igual que

| <= | Menor o igual que

| <> | No igual. Nota: En algunas versiones de SQL este operador puede ser escrito como !=

| BETWEEN | Entre cierto rango

| LIKE | Para consultar los datos basados en información parcial, se utiliza el operador LIKE en la sentencia WHERE. Busca un patrón. El patrón va antes, después o entre un par de % (wildcard). Ejemplo: LIKE 's%' busca cualquier texto que comience con 's'. LIKE '%er' busca cualquier texto que termine con 'er'. Y LIKE '%per%' busca cualquier texto que contenga 'per'.

| IN | Para especificar varios valores posibles para una columna o subquery. Ejemplo de sintaxis cuando se especifica varios valores:

SELECT column1
FROM Table_name
WHERE column1 IN (value1, value2);.

Ejemplo se sintaxis cuando se usa IN en una subquery:

SELECT TrackId, Name, AlbumId
FROM Tracks
WHERE AlbumId IN
    (SELECT AlbumId
    FROM Albums
    WHERE ArtistId = 12);.

## 6.4.1 Práctica: Traer la tabla de países únicamente con Italia
Deben filtrar la tabla de países y traer únicamente a Italy. La tabla de resultados deberá contener los campos id y name de la tabla Country de la base de datos de Fútbol Europeo.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT  *
           FROM Country
           WHERE name  = 'Italy' """

#No modificar lo siguiente:
countries_equal = pd.read_sql(query, conn)
countries_equal

      id   name
0  10257  Italy

## 6.4.2 Práctica: Traer la tabla de países sin Polonia
Deben traer la tabla de países sin Poland. La tabla de resultados deberá contener los campos id y name de la tabla Country de la base de datos de Fútbol Europeo. No se debe utilizar NOT.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT  *
           FROM Country
           WHERE name  <> 'Poland' """

#No modificar lo siguiente:
countries_dif = pd.read_sql(query, conn)
countries_dif

      id         name
0      1      Belgium
1   1729      England
2   4769       France
3   7809      Germany
4  10257        Italy
5  13274  Netherlands
6  17642     Portugal
7  19694     Scotland
8  21518        Spain
9  24558  Switzerland

## 6.4.3 Práctica: Listar los jugadores que pesen entre 174 y 176 libras.
Queremos listar a los jugadores que cumplan con la condición de pesar entre 174 y 176 libras. En la tabla de resultados quiero ver los campos id,player_name, birthday, height y weight de los que cumplen la condición. Todos se encuentran en la tabla Player. Asimismo, debemos limitar la consulta a 30 registros.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT  *
           FROM Player
           WHERE weight BETWEEN 174 AND 176  """

#No modificar lo siguiente:
players_weight = pd.read_sql(query, conn)
players_weight

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,17,161644,Aaron Taylor-Sinclair,213569,1991-04-08 00:00:00,182.88,176
1,34,41093,Abdou Traore,187048,1988-01-17 00:00:00,180.34,174
2,39,191784,Abdoulaye Ba,204826,1991-01-01 00:00:00,198.12,174
3,43,189181,Abdoulaye Diallo,197233,1992-03-30 00:00:00,187.96,174
4,61,24385,Abel Aguilar,177974,1985-01-06 00:00:00,185.42,176
...,...,...,...,...,...,...,...
1180,11056,27305,Zlatan Bajramovic,31667,1979-08-12 00:00:00,182.88,174
1181,11058,12574,Zlatan Ljubijankic,176103,1983-12-15 00:00:00,185.42,176
1182,11065,39801,Zoltan Szelesi,157283,1981-11-22 00:00:00,182.88,176
1183,11072,111182,Zsolt Laczko,164680,1986-12-18 00:00:00,182.88,176
1184,11075,39902,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176

## 6.4.4 Práctica: Listar a los Messi de la base de datos de jugadores.
Queremos listar a los jugadores que cumplan con la condición de tener la palabra 'Messi' en su nombre. En la tabla de resultados quiero ver los campos id,player_name, birthday, height y weight de los que cumplen la condición. Todos se encuentran en la tabla Player.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT id, player_name, birthday, height, weight
           FROM Player
           WHERE player_name like '%Messi%'  """

#No modificar lo siguiente:
players_messi = pd.read_sql(query, conn)
players_messi

     id   player_name             birthday  height  weight
0  6176  Lionel Messi  1987-06-24 00:00:00  170.18     159

## Alias AS
Los alias en SQL se utilizan para dar a una tabla o a una columna, un nombre temporal. Se utilizan a menudo para hacer más legibles los nombres de las columnas. Un alias sólo existe durante la duración de la consulta.

Sintaxis de AS:

SELECT column_name AS alias_name

FROM table_name AS other_alias;

## 7. Sentencia ORDER BY
La sentencia ORDER BY se utiliza para ordenar el conjunto de resultados en orden ascendente o descendente. Por defecto, los registros se ordenan en orden ascendente ASC. Para ordenar los registros en orden descendente, utilice la palabra DESC.

Sintaxis de ORDER BY

SELECT column1, column2, ...

FROM table_name

WHERE condition

ORDER BY column2 ASC|DESC;

## 7.1.1 Ejemplo: Listar a los equipos y ordenarlos por nombre.
Queremos listar a los equipos de la tabla Team y ordenarlos ascedentemente por nombre team_long_name. Adicionalmente, vamos a limitar la lista a 25 registros.

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
query = """SELECT id, team_long_name AS team_name
        FROM Team
        ORDER BY team_long_name ASC
        LIMIT 10;"""
teams_orderby = pd.read_sql(query, conn)
teams_orderby

      id             team_name
0  16848  1. FC Kaiserslautern
1  15624            1. FC Köln
2  16239        1. FC Nürnberg
3  16243       1. FSV Mainz 05
4  11817            AC Ajaccio
5  11074      AC Arles-Avignon
6  49116         AC Bellinzona
7  26560          ADO Den Haag
8   9537            AJ Auxerre
9   9547             AS Monaco

## 7.1.2 Práctica: Listar la tabla de países en orden descendente.
Deben listar la tabla Country de forma descendente DESC por el campos name. La tabla de resultados deberá contener los campos id y name.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT *
        FROM Country
        ORDER BY name DESC
        LIMIT 10; """

#No modificar lo siguiente:
teams_orderdesc = pd.read_sql(query, conn)
teams_orderdesc

      id         name
0  24558  Switzerland
1  21518        Spain
2  19694     Scotland
3  17642     Portugal
4  15722       Poland
5  13274  Netherlands
6  10257        Italy
7   7809      Germany
8   4769       France
9   1729      England

## 7.1.3 Práctica: Listar el id de los 15 jugadores con menos peso.
Deben listar la tabla Player de forma ascendente ASC por el campo weight. La tabla de resultados deberá contener los campos id, player_name y weight.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT id, player_name, weight
        FROM player
        ORDER BY weight ASC
        LIMIT 10; """

#No modificar lo siguiente:
player_weightasc = pd.read_sql(query, conn)
player_weightasc

      id       player_name  weight
0   5453        Juan Quero     117
1   6853   Mariusz Rybicki     121
2  10954   Yohandry Orozco     121
3   1480           Caetano     123
4   2612  Diego Buonanotte     123
5    317       Aldo Kalulu     126
6    655       Andre Horta     126
7   3446      Fouad Rachid     126
8   7258      Maxi Moralez     126
9   7264      Maxime Blanc     126

## 7.1.4 Práctica: Listar el id de los 10 jugadores con mayor estatura
Deben listar la tabla Player de forma descendente DESC por el campos height. La tabla de resultados deberá contener los campos id, player_name y height.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT *
        FROM player
        ORDER BY height DESC
        LIMIT 10; """

#No modificar lo siguiente:
player_heightdesc = pd.read_sql(query, conn)
player_heightdesc

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,5908,148325,Kristof van Hout,185306,1987-02-09 00:00:00,208.28,243
1,1301,150209,Bogdan Milic,189967,1987-11-24 00:00:00,203.20,216
2,1926,103428,Costel Pantilimon,192613,1987-02-01 00:00:00,203.20,212
3,3274,601304,Fejsal Mulic,226114,1994-10-03 00:00:00,203.20,185
4,5568,26585,Jurgen Wevers,148875,1979-01-12 00:00:00,203.20,212
5,5804,96465,Kevin Vink,193674,1984-07-30 00:00:00,203.20,194
6,5957,150297,Lacina Traore,199074,1990-05-20 00:00:00,203.20,192
7,8016,38567,Nikola Zigic,167515,1980-09-25 00:00:00,203.20,212
8,8285,41129,Paolo Acerbis,137130,1981-05-05 00:00:00,203.20,190
9,8638,39522,Pietro Marino,178389,1986-11-21 00:00:00,203.20,209

## 7.1.5 Práctica: Listar el id de los 10 jugadores con mayor estatura y ordenarlos alfabéticamente pero de forma descendente.
Deben listar la tabla Player de forma descendente DESC por el campos height y player_name. La tabla de resultados deberá contener los campos id, player_name y height.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """SELECT id, player_name, height
        FROM player
        ORDER BY height AND player_name DESC
        LIMIT 10; """

#No modificar lo siguiente:
player_height_name = pd.read_sql(query, conn)
player_height_name

   id         player_name  height
0   1  Aaron Appindangoye  182.88
1   2     Aaron Cresswell  170.18
2   3         Aaron Doran  170.18
3   4       Aaron Galindo  182.88
4   5        Aaron Hughes  182.88
5   6          Aaron Hunt  182.88
6   7          Aaron Kuhl  172.72
7   8        Aaron Lennon  165.10
8   9        Aaron Lennox  190.50
9  10       Aaron Meijers  175.26

## 8. Sentencia GROUP BY
La sentencia GROUP BY agrupa las filas que tienen los mismos valores en filas de resumen, como "encontrar el número de clientes en cada país". Se utiliza sobre dimensiones y métricas para agrupar el conjunto de resultados en una o más columnas.

Las dimensiones son todos aquellos valores que estamos describiendo en el SELECT. Y las métricas son que se utilizan a menudo con funciones agregativas (COUNT, MAX, MIN, SUM, AVG).

Sintaxis de GROUP BY;

SELECT column1, column2, ...

FROM table_name

WHERE condition

GROUP BY column1

ORDER BY column2 ASC|DESC;

Nota: El uso de WHERE antes de GROUP BY hace que este se ejecute más rápido, ya que el motor de base de datos no se tomará el tiempo de agrupar cosas que no necesita.

Nota2: Es muy importante utilizar las mismas dimensiones tanto en el SELECT, como en el GROUP BY. De lo contrario, la salida podría ser errónea.

## 8.1.1 Ejemplo: Queremos conocer cuántos equipos tienen cada tipo de velocidad de juego
Queremos conocer cuántos equipos de la tabla Team_Attributes tienen cada tipo de velocidad juego. Es decir: cuántos tienen buildUpPlaySpeedClass = 'Fast', buildUpPlaySpeedClass = 'Balanced' y cuántos buildUpPlaySpeedClass = 'Slow'

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
query = """SELECT buildUpPlaySpeedClass, COUNT(id)
        FROM Team_Attributes
        GROUP BY buildUpPlaySpeedClass;"""
teams_speed = pd.read_sql(query, conn)
teams_speed

  buildUpPlaySpeedClass  COUNT(id)
0              Balanced       1184
1                  Fast        172
2                  Slow        102

## 8.1.2 Práctica: Queremos conocer cuántos equipos tienen cada clase de juego defensivo
Queremos conocer cuantos equipos de la tabla Team_Attributes que tienen cada clase de juego defensivo. Es decir: cuántos defencePressureClass = 'Medium', defencePressureClass = 'Deep' y defencePressureClass = 'High'.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """ SELECT defencePressureClass AS Equipos,
                  COUNT(defencePressureClass) AS Cantidad_Equipos
              FROM Team_Attributes
                  GROUP BY defencePressureClass
                  ORDER BY Cantidad_Equipos DESC """

#No modificar lo siguiente:
teams_defence = pd.read_sql(query, conn)
teams_defence

  Equipos  Cantidad_Equipos
0  Medium              1243
1    Deep               154
2    High                61

## 8.1.3 Práctica: Analítica básica de las temporadas
Queremos realizar un sencillo análisis sobre la tabla Match. Se necesita obtener la siguiente información agrupada por cada season:

- Cuantas stage distintas tuvo y visualizarlo como number_of_stages.
- El promedio de los goles de equipos locales home_team_goal y visualizarlo como avg_home_team_goals
- El promedio de los goles de equipos visitantes away_team_goal y visualizarlo como avg_away_team_goals
- La suma total de goles realizados por los equipos locales y visitantes en la temporada, visualizandolo como total_goals.

Asimismo, se requere ver la información de las temporadas más recientes primero.

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
# Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =
## Cuantas stage distintas tuvo y visualizarlo como number_of_stages

query = """ SELECT stage, COUNT(stage) AS number_of_stages FROM Match
        GROUP BY stage"""

#No modificar lo siguiente:
stages_by_season = pd.read_sql(query, conn)
stages_by_season

    stage  number_of_stages
0       1               740
1       2               740
2       3               740
3       4               740
4       5               740
5       6               740
6       7               738
7       8               738
8       9               738
9      10               738
10     11               738
11     12               738
12     13               738
13     14               738
14     15               738
15     16               738
16     17               738
17     18               738
18     19               737
19     20               737
20     21               737
21     22               736
22     23               735
23     24               737
24     25               737
25     26               730
26     27               730
27     28               737
28     29               736
29     30               733
30     31               578
31     32               578
32     33               578
33     34               578
34     35               407
35     36               407
36     37               368
37     38               367

In [ ]:
# Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =
## El promedio de los goles de equipos locales home_team_goal y visualizarlo como avg_home_team_goals

query = """  SELECT home_team_goal, COUNT(home_team_goal) AS avg_home_team_goals FROM Match
        GROUP BY home_team_goal"""

#No modificar lo siguiente:
avg_home_team_goals = pd.read_sql(query, conn)
avg_home_team_goals

    home_team_goal  avg_home_team_goals
0                0                 5896
1                1                 8400
2                2                 6339
3                3                 3288
4                4                 1385
5                5                  457
6                6                  161
7                7                   38
8                8                    9
9                9                    4
10              10                    2

In [ ]:
# Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =
## El promedio de los goles de equipos visitantes away_team_goal y visualizarlo como avg_away_team_goals

query = """  SELECT away_team_goal,
                    COUNT(away_team_goal) AS avg_away_team_goals
               FROM Match
                    GROUP BY away_team_goal"""

#No modificar lo siguiente:
avg_away_team_goals = pd.read_sql(query, conn)
avg_away_team_goals

   away_team_goal  avg_away_team_goals
0               0                 8687
1               1                 8989
2               2                 5146
3               3                 2145
4               4                  718
5               5                  215
6               6                   63
7               7                   10
8               8                    5
9               9                    1

In [ ]:
# Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =
## La suma total de goles realizados por los equipos locales y visitantes en la temporada, visualizandolo como total_goals.

query = """ SELECT
                  SUM(home_team_goal) AS Total_Goles_Locales,
                  SUM(away_team_goal) AS Total_Goles_Visitantes
                FROM Match
        """

#No modificar lo siguiente:
avg_away_team_goals = pd.read_sql(query, conn)
avg_away_team_goals

   Total_Goles_Locales  Total_Goles_Visitantes
0                40127                   30160

## 9. Sentencias JOIN
JOIN se usa cuando se quiere conectar dos tablas entre sí. Funciona cuando tienes una clave común en cada una de ellas. Entender el concepto de Claves es crucial para conectar (unir) conjuntos de datos (tablas).

Recuerden: Una clave es un valor que podemos usar para referirnos a una fila o registro específico de una tabla. Puede consistir en un valor (celda) que generalmente es un ID, o de una combinación de valores que son únicos en la tabla (clave compuesta).

## Sintaxis de JOIN;

**SELECT first_table.column1, firts_table.column2, second_table.columnA, second_table.columnB ...**

**FROM first_table (LEFT | RIGHT | FULL) JOIN second_table ON first_table.columnID = second_table.columnID;**

## 9.1 Tipos de JOIN
- JOIN: mantiene sólo los registros que coinciden con la condición (después del ON) en ambas tablas, y los registros de ambas tablas que no coincidan, no aparecerían en la tabla de resultado.

- LEFT JOIN: devuelve todos los registros de la primera tabla (izquierda), y los registros coincidentes de la segunda tabla (derecha). El resultado es NULL del lado derecho, si no hay coincidencia.

- RIGHT JOIN: devuelve todos los registros de la segunda tabla (derecha), y los registros coincidentes de la primera tabla (izquierda). El resultado es NULL del lado izquierdo, si no hay coincidencia.

- FULL JOIN: devuelve todos los registros cuando hay una coincidencia en los registros de la primera tabla (izquierda) o segunda tabla (derecha). Nota: FULL JOIN puede potencialmente devolver conjuntos de resultados MUY grandes.

image.png

Cuando se quiere unir diferentes tablas, es necesario que pienses en lo siguiente:

1. Decidir qué tipo de unión usar. Las más comunes son: JOIN y LEFT JOIN.
2. Especificar el valor común que se utiliza para conectar las tablas (la clave).
3. Asegurarse de que al menos uno de los valores tiene que ser una clave en su tabla.

Y por último, ¡Paciencia! Usar los JOIN de forma incorrecta, es el error más común (y a veces peligroso) cuando se escriben consultas complicadas.

## 9.2.1 Ejemplo: Lista de ligas y su país.
Queremos conocer a qué país corresponde cada liga. Para hacerlo, vamos a necesitar la información de las tablas Countryy League, uniendolas por su clave en común: Country.id = League.country_id.

Ejecuta (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
query = """SELECT
               L.id AS Id_League,
               L.name AS Nombre_League,
               C.name AS Pais
        FROM League AS L
            JOIN Country AS C ON C.id = L.country_id;"""

country_leagues = pd.read_sql(query, conn)
country_leagues

    Id_League             Nombre_League         Pais
0           1    Belgium Jupiler League      Belgium
1        1729    England Premier League      England
2        4769            France Ligue 1       France
3        7809     Germany 1. Bundesliga      Germany
4       10257             Italy Serie A        Italy
5       13274    Netherlands Eredivisie  Netherlands
6       15722        Poland Ekstraklasa       Poland
7       17642  Portugal Liga ZON Sagres     Portugal
8       19694   Scotland Premier League     Scotland
9       21518           Spain LIGA BBVA        Spain
10      24558  Switzerland Super League  Switzerland

## 9.2.2 Práctica: Comparación de cantidad de partidos jugados en cierta temporada de España y Bélgica.
Queremos realizar una comparación de la cantidad de partidos jugados en season = '2008/2009' entre los países 'Spain' y 'Belgium'. Los datos necesarios se encuentran en las tablas Match y Country. Asimismo, la tabla de resultados debe visualizarse de la siguiente manera:

- la columna con el nombre del país debe llamarse country_name

- la columna con el conteo de partidos debe llamarse count_matches

- debemos visualizar al país con más partidos jugados en primer lugar

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """ consulta SQL """  después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

query = """ SELECT season AS Fecha, name AS Pais, COUNT(name) AS Cantidad_Partidos
            FROM Match A
            LEFT JOIN Country B ON A.country_id = B.id
            WHERE season = '2008/2009'
            AND name in ('Belgium','Spain')
            GROUP BY name """

#No modificar lo siguiente:
country_matches = pd.read_sql(query, conn)
country_matches

       Fecha     Pais  Cantidad_Partidos
0  2008/2009  Belgium                306
1  2008/2009    Spain                380

## 9.2.3 Práctica: Lista detallada de juegos
Queremos un detalle de 10 juegos realizados en el país Spain, ordenado de forma ascendente por date.

Lo que nos interesa ver es:

- el id del encuentro,
- el Country.name bajo alias country_name,
- el League.name bajo alias league_name,
- season,
- stage,
- date,
- el team_long_name del equipo local bajo alias home_team,
- el team_long_name del equipo visitante bajo alias away_team,
- home_team_goal y
- away_team_goal

Esta información se encuentra repartida entre las tablas: Match, Country, League y Team. Teniendo en cuenta que las claves compartidas entre tablas son estas:

- Country.id = Match.country_id

- League.id = Match.league_id

- Team.team_api_id = Match.home_team_api_id

Para ello deberán escribir la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =

Una vez que estén lo tengan listo, ejecuten (haciendo clic en ejecutar o Shift+Enter) el códido de abajo

Algunas pistas o consejos para el ejercicio: En el ejercicio queremos mostrar sólo las columnas que nos interesan, así que en lugar de * usamos los nombres exactos. Algunas de las columnas tienen el mismo nombre (Ejemplo: Country.name,League.name), por lo que las renombramos usando AS.

Esta consulta tiene algunos JOIN. La razón es que la base de datos utilizada está diseñada en una estructura de estrella. Es decir, tiene una tabla (Match) con todo el "rendimiento del encuentro" y métricas, pero sólo IDs como claves foráneas. Mientras que toda la información descriptiva se encuentra almacenada en otras tablas como: Country, League y Team.

Tengan en cuenta que se puede realizar 2 JOIN con la tabla Team. Esto es un truco, ya que usamos la misma tabla pero básicamente traemos dos copias diferentes de ella, renombrandola con AS. Ejemplo: Team AS HomeTeam y Team AS AwayTeam. La razón es que se necesitaba traer información de goles sobre dos valores diferentes (home_team_api_id y away_team_api_id), y si unimos a la misma tabla, significaría que son iguales entre sí.

También podrías utilizar LEFT JOIN sobre la tabla Team. Depende de si prefieres mantener los datos de los juegos en la tabla de resultados, incluso si uno de los equipos no aparece en la tabla Team.

ORDER BY se podría usar para definir el orden de la tabla de resultados.

In [ ]:
#Ingrese la la consulta SQL entre un par de 3 comillas dobles: """consulta SQL""" después de la palabra query =
query = """ SELECT   A.id,
                     B.name as country_name,
                     C.name as league_name,
                     A.season,
                     A.stage,
                     A.date,
                     D.team_long_name AS home_team,
                     D.team_long_name AS away_team,
                     A.home_team_goal,
                     A.away_team_goal
               FROM Match A
                   LEFT JOIN Country B ON A.country_id = B.id
                   LEFT JOIN League  C ON A.league_id = C.id
                   LEFT JOIN Team    D ON A.home_team_api_id = D.team_api_id
               WHERE B.name = 'Spain'
               ORDER BY A.date DESC
               LIMIT 10 """

#No modificar lo siguiente:
detailed_matches = pd.read_sql(query, conn)
detailed_matches

,id,country_name,league_name,season,stage,date,home_team,away_team,home_team_goal,away_team_goal
0,24490,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,Real Sporting de Gijón,Real Sporting de Gijón,2,0
1,24491,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,Real Betis Balompié,Real Betis Balompié,2,1
2,24492,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,RCD Espanyol,RCD Espanyol,4,2
3,24495,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,Málaga CF,Málaga CF,4,1
4,24497,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,Rayo Vallecano,Rayo Vallecano,3,1
5,24489,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-14 00:00:00,RC Deportivo de La Coruña,RC Deportivo de La Coruña,0,2
6,24493,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-14 00:00:00,Granada CF,Granada CF,0,3
7,24494,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-14 00:00:00,Athletic Club de Bilbao,Athletic Club de Bilbao,3,1
8,24496,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-14 00:00:00,Atlético Madrid,Atlético Madrid,2,0
9,24488,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-13 00:00:00,Valencia CF,Valencia CF,0,1